apiVersion: v1
kind: Service
metadata:
  name: mars-runtime
  labels:
    app.kubernetes.io/part-of: runtime
    app.kubernetes.io/component: runtime
spec:
  selector:
    app.kubernetes.io/component: runtime
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
