//! Garage testcontainer bring-up for s3-compatible integration tests.
//!
//! MARS singles out Garage and SeaweedFS at
//! `crates/adapters/mars-store-s3/src/manifest.rs:195` as the canonical
//! "operator must set allow_non_atomic_publish" backends. SeaweedFS is the
//! simpler image on paper, but `server -s3` fails to bind the master gRPC
//! port in single-container mode in stock builds (upstream issues #6308 and
//! #6542 are open without resolution at time of writing), so the s3
//! sub-server loops forever in connection-refused. Garage is the working
//! alternative.
//!
//! the fixture exposes only primitive fields (no `S3Config`) so this crate
//! stays free of any adapter dependency, which the hexagonal-architecture
//! script enforces.
//!
//! Garage requires a small bootstrap sequence after the daemon starts:
//!   1. discover the node id via `garage status`
//!   2. assign a layout (zone + capacity) to that node
//!   3. apply the staged layout (version 1)
//!   4. create the bucket + key + grant the key access to the bucket
//!
//! `boot_garage` does all four steps inline through the testcontainers exec
//! API so callers only see a ready `GarageFixture`.

use std::io::Write;

use testcontainers::core::ExecCommand;
use testcontainers::{
    ContainerAsync, GenericImage, ImageExt,
    core::{IntoContainerPort, Mount, WaitFor},
    runners::AsyncRunner,
};
use tokio::io::AsyncReadExt;

const CONFIG_TOML: &str = r#"
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
replication_factor = 1
rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "0000000000000000000000000000000000000000000000000000000000000000"
[s3_api]
api_bind_addr = "[::]:3900"
s3_region = "garage"
root_domain = ".s3.garage.localhost"
[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"
[admin]
api_bind_addr = "[::]:3903"
admin_token = "0000000000000000000000000000000000000000000000000000000000000000"
"#;

/// fully booted Garage instance with one bucket pre-created and one key
/// granted r/w access to it. drop the fixture to stop the container.
pub struct GarageFixture {
    container: ContainerAsync<GenericImage>,
    /// http base url for the s3 endpoint, e.g. `http://127.0.0.1:38231`.
    pub endpoint: String,
    /// s3 region declared in the garage config. `AmazonS3Builder` needs
    /// some region even when the server ignores it.
    pub region: String,
    /// access key generated by `garage key create`. ~24 chars.
    pub access_key: String,
    /// secret key paired with `access_key`. 64 hex chars.
    pub secret_key: String,
    /// bucket pre-created and granted read+write to `access_key`.
    pub bucket: String,
    /// keep the host-side config tempdir alive for the container's lifetime
    /// (its toml is bind-mounted into the container).
    #[allow(dead_code)]
    config_dir: tempfile::TempDir,
}

/// overrides for the garage container shape.
#[derive(Debug, Clone)]
pub struct GarageOptions {
    /// image tag for `dxflrs/garage`. defaults to a pinned recent stable.
    pub image_tag: String,
    /// bucket name to create at boot. defaults to `"test"`.
    pub bucket: String,
}

impl Default for GarageOptions {
    fn default() -> Self {
        Self {
            image_tag: "v1.3.1".into(),
            bucket: "test".into(),
        }
    }
}

/// boot a garage container with default options and finish the layout +
/// bucket + key bootstrap. returns a fixture with usable s3 credentials.
pub async fn boot_garage() -> GarageFixture {
    boot_garage_with(GarageOptions::default()).await
}

/// boot a garage container with overridden options.
pub async fn boot_garage_with(opts: GarageOptions) -> GarageFixture {
    let config_dir = tempfile::Builder::new()
        .prefix("mars-garage-cfg-")
        .tempdir()
        .expect("tempdir for garage config");
    let host_config_path = config_dir.path().join("garage.toml");
    {
        let mut f = std::fs::File::create(&host_config_path).expect("create garage.toml");
        f.write_all(CONFIG_TOML.as_bytes()).expect("write garage.toml");
    }
    let host_config = host_config_path.display().to_string();

    let container = GenericImage::new("dxflrs/garage", &opts.image_tag)
        .with_exposed_port(3900.tcp())
        .with_wait_for(WaitFor::message_on_stderr("S3 API server listening"))
        .with_mount(Mount::bind_mount(host_config, "/etc/garage.toml"))
        .start()
        .await
        .expect("docker available; garage container starts");
    let port = container.get_host_port_ipv4(3900).await.expect("garage exposes 3900");
    let endpoint = format!("http://127.0.0.1:{port}");

    // s3 listener may need a beat to actually accept connections after the
    // log line. without this, the first PUT after boot occasionally races.
    tokio::time::sleep(std::time::Duration::from_millis(150)).await;

    let status_out = exec_capture(&container, &["/garage", "status"]).await;
    let node_id = status_out
        .lines()
        .find_map(|line| {
            let token = line.split_whitespace().next()?;
            (token.len() == 16 && token.chars().all(|c| c.is_ascii_hexdigit())).then(|| token.to_owned())
        })
        .expect("garage status produced a node id");

    exec_expect_ok(
        &container,
        &["/garage", "layout", "assign", "-z", "dc1", "-c", "1G", &node_id],
    )
    .await;
    exec_expect_ok(&container, &["/garage", "layout", "apply", "--version", "1"]).await;
    exec_expect_ok(&container, &["/garage", "bucket", "create", &opts.bucket]).await;
    let key_out = exec_capture(&container, &["/garage", "key", "create", "test-key"]).await;
    let access_key = parse_field(&key_out, "Key ID:").expect("garage key create produced a Key ID");
    let secret_key = parse_field(&key_out, "Secret key:").expect("garage key create produced a Secret key");
    exec_expect_ok(
        &container,
        &[
            "/garage",
            "bucket",
            "allow",
            "--read",
            "--write",
            "--owner",
            "--key",
            "test-key",
            &opts.bucket,
        ],
    )
    .await;

    GarageFixture {
        container,
        endpoint,
        region: "garage".into(),
        access_key,
        secret_key,
        bucket: opts.bucket,
        config_dir,
    }
}

async fn exec_capture(container: &ContainerAsync<GenericImage>, argv: &[&str]) -> String {
    let owned: Vec<String> = argv.iter().map(|s| (*s).to_owned()).collect();
    let mut result = container
        .exec(ExecCommand::new(owned.iter().map(String::as_str)))
        .await
        .unwrap_or_else(|e| panic!("docker exec {argv:?} failed to start: {e}"));
    let mut buf = Vec::new();
    result
        .stdout()
        .read_to_end(&mut buf)
        .await
        .unwrap_or_else(|e| panic!("docker exec {argv:?} stdout read failed: {e}"));
    String::from_utf8_lossy(&buf).into_owned()
}

async fn exec_expect_ok(container: &ContainerAsync<GenericImage>, argv: &[&str]) {
    let owned: Vec<String> = argv.iter().map(|s| (*s).to_owned()).collect();
    let mut result = container
        .exec(ExecCommand::new(owned.iter().map(String::as_str)))
        .await
        .unwrap_or_else(|e| panic!("docker exec {argv:?} failed to start: {e}"));
    // drain stdout so the exec stream completes before we check exit code.
    let mut sink = Vec::new();
    let _ = result.stdout().read_to_end(&mut sink).await;
    let code = result
        .exit_code()
        .await
        .unwrap_or_else(|e| panic!("docker exec {argv:?} exit_code: {e}"));
    if !matches!(code, Some(0)) {
        let mut err = Vec::new();
        let _ = result.stderr().read_to_end(&mut err).await;
        panic!(
            "docker exec {argv:?} non-zero exit {code:?}: stdout=`{}` stderr=`{}`",
            String::from_utf8_lossy(&sink),
            String::from_utf8_lossy(&err),
        );
    }
}

fn parse_field(text: &str, key: &str) -> Option<String> {
    text.lines().find_map(|line| {
        let trimmed = line.trim_start();
        trimmed.strip_prefix(key).map(|rest| rest.trim().to_owned())
    })
}

impl GarageFixture {
    /// container id, mainly useful for diagnostics.
    pub fn container_id(&self) -> &str {
        self.container.id()
    }
}
