apiVersion: apps/v1
kind: Deployment
metadata:
  name: mars-compiler
spec:
  template:
    spec:
      containers:
        - name: compiler
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: artifact-store
              mountPath: /var/lib/mars/store
      volumes:
        - name: artifact-store
          persistentVolumeClaim:
            claimName: mars-artifact-store
