apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mars-postgis-data
  labels:
    app.kubernetes.io/part-of: postgis
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mars-artifact-store
  labels:
    app.kubernetes.io/part-of: compiler
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mars-compiler-cache
  labels:
    app.kubernetes.io/part-of: compiler
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mars-compiler-work
  labels:
    app.kubernetes.io/part-of: compiler
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mars-runtime-cache
  labels:
    app.kubernetes.io/part-of: runtime
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mars-fixture
  labels:
    app.kubernetes.io/part-of: fixture-loader
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
