apiVersion: apps/v1
kind: Deployment
metadata:
  name: mars-runtime
spec:
  template:
    spec:
      containers:
        - name: runtime
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - name: artifact-store
              mountPath: /var/lib/mars/store
              readOnly: true
      volumes:
        - name: artifact-store
          persistentVolumeClaim:
            claimName: mars-artifact-store
