#!/usr/bin/env bash
# generate-crd.sh - regenerate the MarsService + MarsServiceCluster CRDs from
# the operator code and stash them under charts/mars-operator/templates/crd.yaml
# as a multi-doc YAML, with the helm resource-policy annotation injected on
# each CRD. CI compares the regenerated output against the committed file to
# catch drift.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${repo_root}/charts/mars-operator/templates/crd.yaml"
tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT

cd "${repo_root}"
cargo run --quiet -p mars-operator -- print-crd > "${tmp}"

{
  echo "# Auto-generated by scripts/generate-crd.sh. Do not edit by hand."
  echo "# Source of truth: bin/mars-operator/src/crd/{spec,cluster}.rs"
  echo "# helm.sh/resource-policy: keep makes helm uninstall leave the CRDs"
  echo "# intact so existing MarsService/MarsServiceCluster objects survive"
  echo "# operator removal."
  # inject the resource-policy annotation under metadata in every doc
  awk '
    /^metadata:/ {
      print
      print "  annotations:"
      print "    helm.sh/resource-policy: keep"
      next
    }
    { print }
  ' "${tmp}"
} > "${out}"

echo "wrote ${out}"
