#!/usr/bin/env bash
# generate-crd.sh - regenerate the MarsService CRD from the operator code and
# stash it under charts/mars-operator/templates/crd.yaml with the helm
# resource-policy annotation prepended. CI compares the regenerated output
# against the committed file to catch drift.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${repo_root}/charts/mars-operator/templates/crd.yaml"
tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT

cd "${repo_root}"
cargo run --quiet -p mars-operator -- print-crd > "${tmp}"

{
  echo "# Auto-generated by scripts/generate-crd.sh. Do not edit by hand."
  echo "# Source of truth: bin/mars-operator/src/crd.rs"
  echo "# helm.sh/resource-policy: keep makes helm uninstall leave the CRD"
  echo "# intact so existing MarsService objects survive operator removal."
  # Inject the resource-policy annotation under metadata.
  awk '
    BEGIN { injected = 0 }
    /^metadata:/ {
      print
      print "  annotations:"
      print "    helm.sh/resource-policy: keep"
      injected = 1
      next
    }
    { print }
  ' "${tmp}"
} > "${out}"

echo "wrote ${out}"
